### PR TITLE
Add themed icon

### LINKED ISSUE #498: Add themed icon
Please add a themed icon (available from android 13+). Because the app icon stands out and looks ugly compared to others.

image

### PR DESCRIPTION
**Pull request by M3DZIK**
closes #498

### CODE REVIEW

**Comment by przemyslawzygmunt** [comment]
Contributor License Agreement is not signed yet.

**Comment by M3DZIK** [comment]
> Contributor License Agreement is not signed yet.

?

**Comment by przemyslawzygmunt** [comment]
You must accept the CLA license in order for us to accept this pull request. You can find a link to it under "Some checks haven't completed yet"

**Comment by M3DZIK** [comment]
> You must accept the CLA license in order for us to accept this pull request. You can find a link to it under "Some checks haven't completed yet"

Why?

**Comment by przemyslawzygmunt** [comment]
This is a condition for PR to be considered.

**Comment by M3DZIK** [comment]
> This is a condition for PR to be considered.

Why is it required?

**Comment by przemyslawzygmunt** [comment]
We do not include sources that are not regulated by law in the project.

**Comment by M3DZIK** [comment]
> We do not include sources that are not regulated by law in the project.

Because? My changes are on gpl2 so I don't see a problem

**Comment by przemyslawzygmunt** [comment]
If the acceptance of the conditions described in the CLA is a problem, this PR will be closed. This is the practice used by many OpenSource projects.

**Pull request closed without merging**
