### PR TITLE
Correcciones de la traducción al español. 

### PR DESCRIPTION
**Pull request by ermaya**

### CODE REVIEW

**Comment by przemyslawzygmunt** [comment]
Please make a pull request from the develop branch to the develop branch. I can also close this PR and manually rewrite your proposed changes. Nevertheless, in both scenarios, please sign the CLA.

**Comment by ermaya** [comment]
I will prefer the second option.
Anyway you should do the same with the translation for supla-ios, it has the same errors.

**Comment by przemyslawzygmunt** [comment]
I merged your changes to develop.
https://github.com/SUPLA/supla-android/commits/develop

For iOS you need to change these files:
https://github.com/SUPLA/supla-ios/tree/develop/SUPLA/es.lproj

The question is can you handle it?

**Comment by ermaya** [comment]
If you give me a couple of days I can review the translation for ios.

**Comment by przemyslawzygmunt** [comment]
Of course, no problem. Just remember to work on the "develop" branch.

**Pull request closed without merging**
